#codecov:
#  require_ci_to_pass: yes

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
  require_base: no
  require_head: yes
#  branches:
#    - main
#    - feature/**