spring:
  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://172.17.0.1:33061/IDE
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: SELECT 1
    hikari:
      maximum-pool-size: 10
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      use_sql_comments: true
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    web: info
    root: info
    org:
      springframework:
        web: info
      hibernate:
        sql: debug
        type: info
        descriptor:
          sql: trace
        orm:
          jdbc:
            bind: trace

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
#  paths-to-match: /*
#  packages-to-scan: *

server:
  port: 9000

jwt_secret: 359ad650b2a631ab4195e2540afa310cd59010b1 # openssl rand -hex 20
